version: "3"
services:
  jd4-1:
    restart: always
    image: jioj/jd4
    privileged: true
    network_mode: host
    container_name: jd4-1
    volumes:
      - ./.cache/1:/root/.cache/jd4
    environment:
      UNAME: judge1
  jd4-2:
    restart: always
    image: jioj/jd4
    privileged: true
    network_mode: host
    container_name: jd4-2
    volumes:
      - ./.cache/2:/root/.cache/jd4
    environment:
      UNAME: judge2
