languages:
  -
    language: cc
    compiler_args: g++ -O2 -Wall -std=c++11 -o /out/main /in/main.cpp -lm
    code_file: main.cpp # not necessary in tarball mode
    execute_file: main # no need to set for an interpreter (will use config in langs.yaml)
    execute_args: main # the execute args for all test cases
  -
    language: c
    compiler_args: gcc -O2 -Wall -std=c11 -o /out/main /in/main.c -lm
    code_file: main.c # not necessary in tarball mode
    execute_file: main # no need to set for an interpreter (will use config in langs.yaml)
    execute_args: main # the execute args for all test cases
test_cases:
  -
    input: input0.txt
    output: output0.txt
    execute_args: -v # the extra execute args appended after the global args
    score: 1
    time_ms: 10
    memory_kb: 16384
  -
    input: input1.txt
    output: output1.txt
    score: 1
    time_ms: 10
    memory_kb: 16384
  -
    input: input2.txt
    output: output2.txt
    score: 1
    time_ms: 10
    memory_kb: 16384
  -
    input: input3.txt
    output: output3.txt
    score: 1
    time_ms: 10
    memory_kb: 16384
  -
    input: input4.txt
    output: output4.txt
    score: 1
    time_ms: 10
    memory_kb: 16384
  -
    input: input5.txt
    output: output5.txt
    score: 1
    time_ms: 10
    memory_kb: 16384
  -
    input: input6.txt
    output: output6.txt
    score: 1
    time_ms: 10
    memory_kb: 16384
  -
    input: input7.txt
    output: output7.txt
    score: 1
    time_ms: 10
    memory_kb: 16384
  -
    input: input8.txt
    output: output8.txt
    score: 1
    time_ms: 10
    memory_kb: 16384
  -
    input: input9.txt
    output: output9.txt
    score: 1
    time_ms: 10
    memory_kb: 16384

